intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libcrails%lib{crails}
import intf_libs += libcrails-attachment%lib{crails-attachment}
import intf_libs += ImageMagick++%lib{Magick++}

lib{crails-image}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-image}:
{
  cxx.export.poptions = "-I$out_root/libcrails-image/" "-I$src_root/libcrails-image/"
  cxx.export.libs = $intf_libs
}

liba{crails-image}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-image}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-image}: bin.lib.version = "-$version.project_id"
else
  lib{crails-image}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
